### ISSUE TITLE
localization of library code

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/orchid#12]
need a solution to localize library code

**Comment by matbme** [comment]
I added a new file inside the application's `core` named `locale.go` with the following code:

```go
package core

type TransFunc func (string, ...interface{}) string
var Trans TransFunc

func SetTrans(trans_func TransFunc) {
    Trans = trans_func
}
```

and then I added this to `main.go`, right before `run()`:

```go
core.SetTrans(abroot.Trans)
```

and every time I want to print a localized string, I run:

```go
Trans("locale.name")
```

It's not part of Orchid but it works. Any idea on how to turn this into a library thing?

**Comment by bketelsen** [comment]
that's super smart! I'll ponder on where that should live for a bit.

**Comment by matbme** [comment]
Not to put pressure, but how's the pondering going?

**Comment by bketelsen** [comment]
I have/had a solution I didn't love, then I got distracted by a wandering squirrel.
